# Generated by Django 3.0.2 on 2020-01-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='coupan_code',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.CharField(max_length=220),
        ),
    ]
